blank_issues_enabled: false
contact_links:
  - name: Submit a new POI (PlanetPOI Registry)
    url: https://bbbkada.github.io/EDMC-PlanetPOI/
    about: Use the PlanetPOI registry page to submit new locations.
